apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: env
                    operator: In
                    values: ["dev", "qa"]
          - git:
              repoURL: https://github.com/mtweeman/argo-cd-test.git
              revision: HEAD
              directories:
                - path: apps/*
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{index .path.segments 1}}'
#      finalizers:
#        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://github.com/mtweeman/argo-cd-test.git
          path: '{{.path.path}}/envs/{{index .metadata.labels "env"}}'
          targetRevision: HEAD
          helm:
            valueFiles:
              - $values/values/{{index .path.segments 1}}/envs/{{index .metadata.labels "env"}}-values.yaml
        - repoURL: https://github.com/mtweeman/argo-cd-test.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true